version: 2

jobs:
  build:
    docker:
      - image: rustlang/rust:nightly

    steps:
      - checkout
      - restore_cache:
          key: cache
      - run:
          name: Build
          command: |
            rustc --version
            cargo --version
            cargo build
      - save_cache:
          key: cache
          paths:
            - "~/.cargo"
            - "./target"

  lint_and_format:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - restore_cache:
          key: cache
      - run:
          name: Check code format
          command: |
            rustup component add rustfmt-preview
            rustfmt --version
            cargo fmt

  test:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - restore_cache:
          key: cache
      - run:
          name: Run Test
          command: cargo test

  deplay:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - restore_cache:
          key: cache
      - run:
          name: Cargo release
          command: |
            cargo login $crate_io
            cargo publish

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - lint_and_format:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy-approval:
          type: approval
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}/
      - deplay:
          requires:
            - deploy-approval
          filters:
            branches:
              only: master
            tags:
              only: /.*/
